### ISSUE TITLE
browserslist is spelled wrong

### ISSUE THREAD

**Issue by ghost** [coding-in-public/astro-blog-tutorial#2]
Hi there! Thank you for the awesome tutorials! I'm wanting to make my own personal website/blog using Astro so I'm trying to learn all I can before I dig in.

So, I forked the repo, fixed the typo in all the branches, but now I don't know what I should do next.

It looks like I'd have to open a pull request for each branch. Is that right? Is that what I should do? I love helping out but I'm still kinda new at this.

Do you want me to open like 13 pull requests? lol

**Comment by coding-in-public** [comment]
Ah! I'll do it. No worries. Sorry for the trouble 🤦‍♂️
