### ISSUE TITLE
css

### ISSUE THREAD

**Issue by herediiaa** [coding-in-public/astro-blog-tutorial#3]
hi, i am gaving problerms with my css, it give me like 84 expected and I do not know what i have to do.

**Comment by herediiaa** [comment]
i had to change my style document (global.css to global.scss)

**Comment by kwibus2000** [comment]
Changing the extension .css to .scss does not work. Although the number of problems is only 8 after that, these problems are worse; the app won't run!

**Comment by coding-in-public** [comment]
@herediiaa, you may get some syntax errors, but if you follow the steps I outlined, it should still work accurately. Changing to scss will only cause other problems—as it's not written in scss. If you'd like to remove the syntax errors, you can install an extension for PostCSS (here's one: https://marketplace.visualstudio.com/items?itemName=csstools.postcss)

**Comment by coding-in-public** [comment]
@kwibus2000 Correct, it's not scss, so changing to that extension will only cause more problems. :)
